spring.freemarker.cache: false
spring.servlet.multipart:
  enabled: true
  max-file-size: 1MB
  max-request-size: 1MB

logging.level.root: DEBUG

spring.profiles.default: local

---

spring.profiles.group.local:
  - eth-local
  - adnetwork-contract-local

---

spring.profiles.group.beta:
  - eth-beta
  - adnetwork-contract-beta
